version: '3'
services:
  rw:
    image: jmalloc/echo-server
    ports:
      - "8080:8080"
  ro:
    image: jmalloc/echo-server
    ports:
      - "8081:8080"
  envoy:
    build: .
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
    depends_on:
      - ro
      - rw
  sh:
    image: ubuntu


  
